### ISSUE TITLE
Error returned when repo path is more than two levels deep

### ISSUE THREAD

**Issue by taylor-madeak** [vmware/carbon-black-adapter-for-harbor#16]
### Describe the bug

Scanner fails to pull the image when the image path has more than two elements.  E.g. `library/ubi8/python-39`.  This is a common configuration for Harbor proxy-cache repositories, though by no means unique to this scenario.  This issue occurs for both normal and proxy-cache repositories.

Full log output returned by Harbor:
```
2023-11-10T23:38:17Z [INFO] [/pkg/scan/job.go:387]: {
  "uuid": "5dbac9a9-7f73-11ee-b2f5-5a0015c37d65",
  "name": "Carbon Black",
  "description": "",
  "url": "http://cb-harbor-adapter.carbonblack.svc:8080",
  "disabled": false,
  "is_default": true,
  "health": "healthy",
  "auth": "",
  "access_credential": "[HIDDEN]",
  "skip_certVerify": false,
  "use_internal_addr": true,
  "adapter": "Carbon-Black",
  "vendor": "VMware",
  "version": "1.0",
  "create_time": "2023-11-10T02:46:36.555415Z",
  "update_time": "2023-11-10T02:53:36.90597Z"
}
2023-11-10T23:38:17Z [INFO] [/pkg/scan/job.go:387]: {
  "registry": {
    "url": "http://harbor-dev-core:80",
    "authorization": "[HIDDEN]"
  },
  "artifact": {
    "namespace_id": 3,
    "repository": "test/ubi8/python-39",
    "tag": "latest",
    "digest": "sha256:11d0b758d1d8b26e673892bd6651426aa4a52853f331263e9fb2e017a18b5517",
    "mime_type": "application/vnd.docker.distribution.manifest.v2+json"
  }
}
2023-11-10T23:38:17Z [INFO] [/pkg/scan/job.go:167]: Report mime types: [application/vnd.scanner.adapter.vuln.report.harbor+json; version=1.0 application/vnd.security.vulnerability.report; version=1.1]
2023-11-10T23:38:17Z [ERROR] [/pkg/scan/job.go:370]: scan job: submit scan request: v1 client: submit scan: Scan failed: Expected exactly 2 substrings but found 3: general response handler: unexpected status code: 500, expected: 202
```

Log output from the harbor-adapter (log_level: error) pod doesn't really have anything useful:

```
[GIN] 2023/11/11 - 00:53:04 | 200 |      51.051µs |     172.20.1.51 | GET      "/api/v1/metadata"
[GIN] 2023/11/11 - 00:53:16 | 500 |       80.38µs |     172.20.2.76 | POST     "/api/v1/scan"
```

### Reproduction steps

Steps assume the following:
- CB harbor-adapter has been deployed in a pod on the same cluster (but not necessarily the same namespace) as Harbor.
- CB harbor-adapter has been added to Harbor as an interrogation source and set as default.

1. Pull `registry.access.redhat.com/ubi8/python-39:latest`.
2. Re-tag the image for Harbor.  e.g. `docker tag registry.access.redhat.com/ubi8/python-39:latest harbor.example.com/library/ubi8/python-39:latest`.
3. Push the image to Harbor.
4. Trigger a manual scan in the `library` project.

### Expected behavior

I'm just now testing this product, but my assumption is that the scan data returned will be something like the builtin Trivy scanner.  At least a successful HTTP code.

### Additional context

I believe the bug to be here:
https://github.com/vmware/carbon-black-adapter-for-harbor/blob/ea2ec76178df2829f5e268df08645caf24eb74de/internal/adapter/imagescanning/adapter.go#L89-L93

**Comment by ltsonov-cb** [comment]
Thank you for reporting this. It will be fixed in the next release.

**Comment by ltsonov-cb** [comment]
The fix is now on the main branch Please validate and re-open the issue if the problem persists.

**Comment by taylor-madeak** [comment]
@ltsonov-cb I'm reopening simply because I'm unable to deploy an update with a rollout to test - FluxCD, Helm, and K8S all tell me that no upgrade is available based on Helm chart version.  Please bump the Helm chart version.

**Comment by ltsonov-cb** [comment]
@taylor-madeak good point, thanks for the reminder. Version is bumped so tools should pull the latest version now.

**Comment by taylor-madeak** [comment]
@ltsonov-cb I see the new chart version now, but the adapter is still returning the exact same error.  I can change pull policy to Always for testing, but the chart sets the default pull policy for the deployment to IfNotPresent.  The issue appears to be in [helm/values.yaml#L5](https://github.com/vmware/carbon-black-adapter-for-harbor/blob/f89d1e8cdce9e84b900c45506776055daecae8a1/helm/values.yaml#L5).  Did you publish a new tag in the registry when the container was updated?

**Comment by ltsonov-cb** [comment]
@taylor-madeak 

We pushed the 2.1 tag but the chart is hardcoded so building the image did not change it. 
That is the problem with quick onboarding to a project I guess. 

2.1 is available on harbor and the chart is bumped as well. Let me know if you hit more issues.

**Comment by taylor-madeak** [comment]
@ltsonov-cb 

Looks like publishing the new tag and updating the deployment spec for the chart resolved that issue.  I can confirm that the adapter has been able to successfully scan images with more than two path elements in all of the tests I've performed so far.  Good job!
